
CREATE DATABASE Today_Feelings;
USE Today_Feelings;



CREATE TABLE `Users` (
	`uid` INT NOT NULL AUTO_INCREMENT,
	`id` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`password` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`name` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`sex` TINYINT NOT NULL,
	`email` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`uid`) USING BTREE,
	UNIQUE INDEX `id` (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE `Userdata` (
	`userUID` INT NOT NULL,
	`anger` BINARY(10) NULL DEFAULT '0000000001',
	`fear` BINARY(10) NULL DEFAULT '0000000001',
	`happiness` BINARY(10) NULL DEFAULT '0000000001',
	`sadness` BINARY(10) NULL DEFAULT '0000000001',
	`surprise` BINARY(10) NULL DEFAULT '0000000001',
	PRIMARY KEY (`userUID`) USING BTREE,
	CONSTRAINT `FK3` FOREIGN KEY (`userUID`) REFERENCES `Today_Feelings`.`Users` (`uid`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `Playlists` (
	`uid` INT NOT NULL AUTO_INCREMENT,
	`urlWeb` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`title` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`genre` INT NOT NULL DEFAULT '10',
	PRIMARY KEY (`uid`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE `Statistics` (
	`uid` INT NOT NULL AUTO_INCREMENT,
	`userUID` INT NULL DEFAULT NULL,
	`dateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`songUID` INT NULL DEFAULT NULL,
	`emotion` TINYINT NULL DEFAULT NULL,
	PRIMARY KEY (`uid`) USING BTREE,
	INDEX `FK1` (`userUID`) USING BTREE,
	INDEX `FK2` (`songUID`) USING BTREE,
	CONSTRAINT `FK1` FOREIGN KEY (`userUID`) REFERENCES `Today_Feelings`.`Users` (`uid`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `FK2` FOREIGN KEY (`songUID`) REFERENCES `Today_Feelings`.`Playlists` (`uid`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;