FROM python:latest
RUN mkdir Flask_server/
RUN apt-get update -y
RUN apt-get install vim -y
COPY ./Flask_server Flask_server
WORKDIR /Flask_server/
RUN pip install -r requirements.txt
EXPOSE 10081

ENTRYPOINT tail -f /dev/null
