name: flask-main-run-action
on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on : ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses : actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./web/dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web_sever:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        working-directory: ${{ env.working-directory }}
