# name : Sync and merge upstream repository
# on : 
#   workflow_dispatch:
#   schedule:
#   - cron : '15 * * * * '

# jobs:
#   merge:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Merge upstream
#         run: |
#           git config --global user.name 'dksj9921'
#           git config --global user.email 'sung980213@naver.com'
#           # "git checkout master" is unnecessary, already here by default
#           git pull --unshallow  # this option is very important, you would get
#                                 # complains about unrelated histories without it.
#                                 # (but actions/checkout@v2 can also be instructed
#                                 # to fetch all git depth right from the start)
#           git remote add upstream https://github.com/Gocha64/Today_Feeling.git
#           git fetch upstream
#           git checkout main
#           git merge -Xtheirs upstream/main
#           git push origin main
#           # etc


name: Trigger Workflow on Repository Change

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetches all git history

      - name: Check if upstream is ahead of forked repository
        id: diff
        run: |
          git remote add upstream https://github.com/Gocha64/Today_Feeling.git
          git fetch upstream
          git fetch origin
          if [ $(git rev-parse HEAD) = $(git rev-parse @{u}) ]; then
            echo "Up-to-date"
            exit 0
          else
            echo "::set-output name=diff::$(git log --pretty=format:'%h' origin..upstream)"
            exit 1
          fi

      - name: Create Pull Request
        if: steps.diff.outputs.diff != ''
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "update-${{ github.event_name }}-${{ github.sha }}"
          title: "Update from upstream"
          body: "Changes from upstream: ${{ steps.diff.outputs.diff }}"
          commit-message: "Update from upstream"
          labels: "auto-update"


