FROM nginx
RUN mkdir /app
RUN apt-get update -y
RUN apt-get install vim -y
WORKDIR /app
RUN mkdir ./build
COPY ./Web/build ./build
RUN rm /etc/nginx/conf.d/default.conf
COPY ./Web/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
